config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "genres#index"
  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end
  resources :genres do
    collection do
      get :display_categories
    end
  end
  resources :categories do
    collection do
      get :search
    end
    resources :talks, only: :index
  end
  resources :talks, except: [:index, :new] do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  post '/category_users' => "category_users#create"
  delete '/category_users' => "category_users#destroy"
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy

  validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
    @category = Category.find(params[:category_id])
    @talks = @category.talks.order('id DESC')
  end

  def create
    talk = current_user.talks.new(talk_params)
    if talk.save
      redirect_to category_talks_path(talk_params[:category_id])
    end
  end

  def show
    @talk = Talk.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy
    redirect_to category_talks_path(@talk.category)
  end

  private

  def talk_params
    params.require(:talk).permit(:content, :category_id)
  end
end

app/views/talks/_like.html.haml
- if user_signed_in?
  - if Like.find_by(user_id: current_user.id, talk_id: talk.id)
    = link_to talk_likes_path(talk), method: :delete, remote: true do
      = icon 'fas', 'star'
  - else
    = link_to talk_likes_path(talk), method: :post, remote: true do
      = icon 'far', 'star'
  = talk.likes.count
- else
  = icon 'far', 'star'
  = talk.likes.count

app/views/talks/_talk.html.haml
.talk-content
  .left-content
    .left-content__head
      %ul
        %li
          = link_to talk.user.nickname, user_path(talk.user)
        - if user_signed_in? && talk.user == current_user
          %li
            = link_to '削除', talk_path(talk), method: :delete, data: {confirm: "削除しますか？"}
    = link_to talk_path(talk) do
      .left-content__text
        = simple_format(talk.content)
  .right-content
    .right-content__head
      = talk.created_at.strftime("%Y/%m/%-d %H:%M")
    .right-conent__list
      .comments
        = link_to talk_path(talk) do
          = icon 'far', 'comment'
        = talk.comments.length
      .likes{id: "talk-" + talk.id.to_s}
        = render partial: 'talks/like', locals: {talk: talk}

app/views/talks/index.html.haml
.talk-title
  .talk-title__category
    %span
      = @category.name
    = icon 'fas', 'users'
    = @category.category_users.length
  .talk-title__join
    - if user_signed_in?
      - if CategoryUser.find_by(category_id: @category.id, user_id: current_user.id)
        = link_to "参加をやめる", category_users_path(category_id: @category.id), method: :delete
      - else
        = link_to "参加する！", category_users_path(category_id: @category.id), method: :post
    - else
      = link_to "参加する！", new_user_session_path

= render @talks

app/views/talks/show.html.haml
.back-link
  = link_to "トークに戻る", category_talks_path(@talk.category)

= render @talk

.comment__index
  .comment__index--title
    コメント(
    = @talk.comments.length
    )
  .comment__index--comments
    - @talk.comments.each do |comment|
      .talk-content
        .left-content
          .left-content__head
            %ul
              %li
                = link_to comment.user.nickname, user_path(comment.user)
              - if user_signed_in? && comment.user == current_user
                %li
                  = link_to '削除', talk_comment_path(comment.talk, comment), method: :delete, data: {confirm: "削除しますか？"}
          .left-content__text
            = simple_format(comment.content)
        .right-content
          .right-content__head
            = comment.created_at.strftime("%Y/%m/%-d %-H:%M")

.bottom-content
  = form_with model: [@talk, @comment], local: true do |f|
    .comment__new
      .comment__new--area
        = f.text_area :content
      .comment__new--submit
        = f.submit :コメント