config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "genres#index"
  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end
  resources :genres do
    collection do
      get :display_categories
    end
  end
  resources :categories do
    collection do
      get :search
    end
    resources :talks, only: :index
  end
  resources :talks, except: [:index, :new] do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  post '/category_users' => "category_users#create"
  delete '/category_users' => "category_users#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :talks, dependent: :destroy
  has_many :categories, through: :category_users
  has_many :category_users, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :nickname, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: {in: 6..128}

  enum sex: {
    "男": 0,
    "女": 1,
    "その他": 2
  }

  enum address: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.find(params[:id])
    @categories = []
    @user.category_users.each do |category_user|
      @categories << category_user.category
    end
  end

  def search
    @age = params[:q][:birthday_in]
    @q = User.search(search_params)
    unless @age
      @result_users = @q.result(distinct: true)
    else
      @users = @q.result(distinct: true)
      @result_users = @users.select do |user|
        @age.include?("#{birthday_to_age(user.birthday)}")
      end
    end
  end

  private

  def search_params
    params.require(:q).permit(:nickname_cont, {sex_in: []}, {birthday_in: []}, {address_in: []})
  end
end

app/helpers/user_helper.rb
module UserHelper
  def birthday_to_age(birthday)
    user_age = (Date.today.strftime("%Y%m%d").to_i - birthday.strftime("%Y%m%d").to_i) / 10000
    if user_age >= 60
      5
    elsif user_age >= 50
      4
    elsif user_age >= 40
      3
    elsif user_age >= 30
      2
    elsif user_age >= 20
      1
    else
      0
    end
  end

  def show_age(birthday)
    if birthday_to_age(birthday) == 5
      "60代以上"
    elsif birthday_to_age(birthday) == 4
      "50代"
    elsif birthday_to_age(birthday) == 3
      "40代"
    elsif birthday_to_age(birthday) == 2
      "20代"
    elsif birthday_to_age(birthday) == 1
      "20代"
    else
      "未成年"
    end
  end
end

app/views/users/index.html.haml
.search-title
  ユーザー検索

= search_form_for(@q, url: search_users_path) do |f|
  .search-content
    .search-field
      = f.label :nickname_cont, 'ユーザー名'
      %br
      = f.search_field :nickname_cont

    .search-field
      = f.label :birthday_in, "年代"
      %br
      %label
        = f.check_box :birthday_in, {multiple: true}, 0, nil
        = f.label "未成年"
      %label
        = f.check_box :birthday_in, {multiple: true}, 1, nil
        = f.label "20代"
      %label
        = f.check_box :birthday_in, {multiple: true}, 2, nil
        = f.label "30代"
      %label
        = f.check_box :birthday_in, {multiple: true}, 3, nil
        = f.label "40代"
      %label
        = f.check_box :birthday_in, {multiple: true}, 4, nil
        = f.label "50代"
      %label
        = f.check_box :birthday_in, {multiple: true}, 5, nil
        = f.label "60代以上"

  
    .search-field
      = f.label :sex_in, "性別"
      %br
      - User.sexes.each do |i|
        = f.check_box :sex_in, {multiple: true}, i[1], nil
        = f.label "#{i[0]}"
    
    .search-field
      = f.label :address_in, "都道府県"
      %br
      - User.addresses.each do |i|
        = f.check_box :address_in, {multiple: true}, i[1], nil
        = f.label "#{i[0]}"
  
    .search-field
      = f.submit

app/views/users/search.html.haml
.search-title
  検索結果

- if @result_users.present?
  - @result_users.each do |user|
    = link_to user_path(user) do
      .search-result
        = user.nickname
        - if user.sex
          = user.sex
          \/
        - if user.birthday
          = show_age(user.birthday)
          \/
        - if user.address
          = user.address
- else
  %p 該当するユーザーはいません

app/views/users/show.html.haml
.user__name
  - if @user == current_user
    .user__name--edit
      = @user.nickname
      = link_to edit_user_registration_path do
        = icon 'fas', 'user-cog'
    = link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} do
      = icon 'fas', 'sign-out-alt'
  - else
    = @user.nickname

.user__detail
  - if @user.sex
    = @user.sex
    \/
  - if @user.birthday
    = show_age(@user.birthday)
    \/
  - if @user.address
    = @user.address

.user__profile
  = simple_format(@user.profile)

.user__categories
  - @categories.each do |category|
    .user__categories--list{data: {categoryid: category.id}}
      = category.name

.user__talks
  - @categories.each do |category|
    .user__talks--lists.display_none{data: {categoryid: category.id}}
      = render partial: 'talks/talk', collection: Talk.where(user_id: @user.id, category_id: category.id), as: :talk