config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "genres#index"
  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end
  resources :genres do
    collection do
      get :display_categories
    end
  end
  resources :categories do
    collection do
      get :search
    end
    resources :talks, only: :index
  end
  resources :talks, except: [:index, :new] do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  post '/category_users' => "category_users#create"
  delete '/category_users' => "category_users#destroy"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :genre
  has_many :talks, dependent: :destroy
  has_many :users, through: :category_users
  has_many :category_users, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]

  def index
  end
  
  def create
    category = Category.new(category_params)
    if category.save
      flash[:success] = "作成しました！"
      redirect_to root_path
    else
      render 'genre/index'
    end
  end

  def show
    @talks = Talk.where(category_id: params[:id])
  end

  def search
    @result_genres = Genre.where('name LIKE(?)',  "%#{params[:name]}%")
    @result_categories = Category.where('name LIKE(?)',  "%#{params[:name]}%")
  end

  private
  def category_params
    params.require(:category).permit(:name, :genre_id)
  end
end

app/views/categories/index.html.haml
.search-title
  カテゴリー検索

= form_with url: search_categories_path, method: :get, local: true do |f|
  .search-content
    .search-field
      = f.text_field :name
    .search-field
      = f.submit "検索"

app/views/categories/search.html.haml
.search-title
  検索結果

.search-result
  - if @result_genres.present?
    .result__title
      ジャンル
    .result__genre
      %ul.result__content
        - @result_genres.each do |genre|
          %li.genre_name{data: {id: genre.id}}
            = genre.name
      %ul#category_area

.search-result
  - if @result_categories.present?
    .result__title
      カテゴリー
    %ul.result__content
      - @result_categories.each do |category|
        %li
          = link_to category.name, category_talks_path(category)