config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "genres#index"
  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end
  resources :genres do
    collection do
      get :display_categories
    end
  end
  resources :categories do
    collection do
      get :search
    end
    resources :talks, only: :index
  end
  resources :talks, except: [:index, :new] do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  post '/category_users' => "category_users#create"
  delete '/category_users' => "category_users#destroy"
end

app/views/layouts/_new_talk.html.haml
- if user_signed_in?
  .new-talk__head
    .new-talk__head--title
      Let's talk !
    .new-talk__head--cancel
      = icon 'fas', 'times-circle'

  .new-talk__content
    = form_with model: @talk, local: true do |f|
      = f.collection_select :category_id, @select_lists, :id, :name, {prompt: '---'}
      %br
      = f.text_area :content
      %br
      = f.submit "投稿"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title スキトーク！
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header__main
        .title
          = link_to "スキトーク！", root_path
        - if user_signed_in?
          .links
            = link_to user_path(current_user) do
              .links__link
                = icon 'fas', 'user'
            .links__link.new_talk_btn
              = icon 'fas', 'edit'
        - else
          .links
            = link_to new_user_registration_path do
              .links__link
                %p 登録
            = link_to new_user_session_path do
              .links__link
                %p login
        .links__link#search_icon
          = icon 'fas', 'search'
          %ul#search_links.display_none
            %li= link_to "ユーザー検索", users_path
            %li= link_to "カテゴリ検索", categories_path
      - if user_signed_in?
        .header__sub
          - @categories.each do |category|
            .header__sub--list
              = link_to category.name, category_talks_path(category)

    %main
      .container
        = yield
      .shadow.display_none
      .new-talk.display_none
        = render 'layouts/new_talk'